---
title: "Task_5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- The tidyverse package needs to be loaded every time it's used. However, it only needs to be installed once.

- A data frame is a rectangular collection of variables (in the columns) and observations (in the rows). 

- Graphing templates can be used repeatedly by substituting some of the bracketed sections.

- An aestetic is a visual property of the objects in your plot. They can include the size, shape, or color of your points.

- When you map an aesthetic, you associate the name of the aesthetic to the name of the variable, and automatically assign a unique level of aesthetic to each unique value of the variable.

- Facets are subplots that each display one subset of the data.

- A geom is the geometrical object that a plot uses to represent data. 

- A stat or statistical transformation is used to calculate new values for a graph.

- Overplotting happens when many points appear on a grid and overlap each other. 

